# Generated by Django 3.2.4 on 2022-02-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costs',
            old_name='cost',
            new_name='price',
        ),
    ]
