# Generated by Django 3.2.4 on 2022-02-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_cost_costs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='name',
            field=models.CharField(max_length=34, verbose_name='Nome'),
        ),
    ]
