# Generated by Django 3.2.4 on 2022-02-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_costs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='description',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
    ]
